# Generated by Django 3.2.4 on 2021-07-14 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='category',
            field=models.CharField(choices=[('', 'Select...'), ('Login', 'Login'), ('Secure Note', 'Secure Note'), ('Credit Card', 'Credit Card'), ('Passport', 'Passport'), ('Personal Information', 'Personal Information')], default='Login', max_length=25),
        ),
        migrations.AlterField(
            model_name='account',
            name='vault',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='backend.vault'),
        ),
    ]
