# Generated by Django 3.2.4 on 2021-07-14 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210714_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='category',
        ),
    ]
